# Generated by Django 4.2.1 on 2023-05-21 14:22

import characters.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="csv_file",
            field=models.FileField(
                upload_to=characters.models.RandomFileName("characters/")
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
